richsalz/draft-ietf-uta-rfc6125bis

draft-ietf-uta-rfc6125bis.md
Trivial editorial, not going to wait for comments.
=> Remove extra/spurious blank lines

draft-ietf-uta-rfc6125bis.md
Update TLS and DTLS RFC's, remove references to SSL.
Also update some obsolete RFC references.
=> SNI is not new.

draft-ietf-uta-rfc6125bis.md
Also simplify wording around what is out of scope.
Fixes: #8
=> Remove "global directory" and related

draft-ietf-uta-rfc6125bis.md
Remove ">" text, or rewrite it so it fits inline more naturally.
=> Rewrite/remove "> xxx" text.

draft-ietf-uta-rfc6125bis.md
Consult the diff.
Also added words to fix two issues folks have reported.
Fixes: #22, #21
=> Wordsmith introduction section.

draft-ietf-uta-rfc6125bis.md
Based on #23, so only look at the latest commit(s).
=> Wordsmith naming section

draft-ietf-uta-rfc6125bis.md
This is based on #24 so only look at the latest commit(s).
=> Wordsmith design section

draft-ietf-uta-rfc6125bis.md
to be discussed on the email list?
=> Viktor's feedback on PR #23

draft-ietf-uta-rfc6125bis.md
Based on #26 so only look at the latest commits.
=> Edit 'requesting server certificates' section

draft-ietf-uta-rfc6125bis.md
=> Various editorial tweaks.

draft-ietf-uta-rfc6125bis.md
Fix https://github.com/richsalz/draft-ietf-uta-rfc6125bis/issues/39
=> remove text about third-party domain mapping

draft-ietf-uta-rfc6125bis.md
=> change Jeff's affiliation and email address

draft-ietf-uta-rfc6125bis.md
Taken from https://github.com/richsalz/draft-ietf-uta-rfc6125bis/pull/29#discussion_r722367686
and made into its own PR.
=> Add Ryan's text about multiple identifiers

draft-ietf-uta-rfc6125bis.md
Address https://github.com/richsalz/draft-ietf-uta-rfc6125bis/issues/44
=> more examples

draft-ietf-uta-rfc6125bis.md
Address Martin's concern about Alpaca and cross-protocol attacks and
multiple SAN entries in a cert.
Fixes: 43
=> Point to RFC7525bis

draft-ietf-uta-rfc6125bis.md
Fixes https://github.com/richsalz/draft-ietf-uta-rfc6125bis/issues/55
=> correct text about reg-name

draft-ietf-uta-rfc6125bis.md
Fixes https://github.com/richsalz/draft-ietf-uta-rfc6125bis/issues/63
=> first cut at clarifying generation of reference identifiers

draft-ietf-uta-rfc6125bis.md
* add ref to gTLD Applicant Guidebook
* fix some leftovers pre IP-ID edits
* fix a few typos
Signed-off-by: Thomas Fossati <thomas.fossati@arm.com>
=> typographical fixes and a missing reference

draft-ietf-uta-rfc6125bis.md
Fixes https://github.com/richsalz/draft-ietf-uta-rfc6125bis/issues/75
=> domain name text

draft-ietf-uta-rfc6125bis.md
Fixes https://github.com/richsalz/draft-ietf-uta-rfc6125bis/issues/76
=> improvements to the security considerations

draft-ietf-uta-rfc6125bis.md
Fixes https://github.com/richsalz/draft-ietf-uta-rfc6125bis/issues/72
=> improve text about delegated domains

draft-ietf-uta-rfc6125bis.md
Fixes https://github.com/richsalz/draft-ietf-uta-rfc6125bis/issues/83
=> initial pass at addressing feedback from John Klensin

draft-ietf-uta-rfc6125bis.md
=> Simplify *.example.com notation

draft-ietf-uta-rfc6125bis.md
Sorry the apps I use don't let me enter accents properly (terminal and vim).  Špaček.  Sigh.
=> Petr Spacek's feedback from DNS Directorate

draft-ietf-uta-rfc6125bis.md
Fixes https://github.com/richsalz/draft-ietf-uta-rfc6125bis/issues/94
=> changes to address nits from GENART review

draft-ietf-uta-rfc6125bis.md
Fixes https://github.com/richsalz/draft-ietf-uta-rfc6125bis/issues/95
=> address security concern in OPSDIR review

draft-ietf-uta-rfc6125bis.md
Fixes https://github.com/richsalz/draft-ietf-uta-rfc6125bis/issues/99
=> Part 2 of Éric Vynke's feedback

draft-ietf-uta-rfc6125bis.md
IPv6, address literals and examples.
Also fix some trailing whitespace lint
Fixes: #101
=> Address Erik Nygren's points

draft-ietf-uta-rfc6125bis.md
Fixes https://github.com/richsalz/draft-ietf-uta-rfc6125bis/issues/98
=> text from @bemasc with further massaging

draft-ietf-uta-rfc6125bis.md
This addresses feedback from Lars Eggert.
*DO NOT MERGE*  There is still one open item, about the use of "traditional DNS names" (not-international).
Edit: *OKAY TO MERGE* once we're satisfied.
Fixes #104
=> Lars's feedback

draft-ietf-uta-rfc6125bis.md
Fixes https://github.com/richsalz/draft-ietf-uta-rfc6125bis/issues/107
=> use .example domains

draft-ietf-uta-rfc6125bis.md
=> Address Warren's feedback.

draft-ietf-uta-rfc6125bis.md
Fixes https://github.com/richsalz/draft-ietf-uta-rfc6125bis/issues/111
=> remove extraneous note about TLDs

rfc9525.xml
Further edits to come, let's not merge until AUTH48 is done.
=> AUTH48 edits
